[package]
name = "rustencils"
version = "0.1.0"
authors = ["agilman0803 <agilman@princeton.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13.1"